apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spatial-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PandhuWibowo/apps-manifest.git
    targetRevision: HEAD
    path: spatial-service
    helm:
      valueFiles:
        - values-dev.yaml  # Ensure the correct values file is being used here
  destination:
    server: 'https://nonprod-global-oq8qkdbr.hcp.southeastasia.azmk8s.io:443'
    namespace: analytics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
