apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spatial-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PandhuWibowo/apps-manifest.git
    targetRevision: 0.1.0
    chart: app-deployment/spatial-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: "operationtoolsgeneralbvarta.azurecr.io/analytics-service"
        - name: image.tag
          value: "latest"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: analytics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
