apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PandhuWibowo/apps-manifest.git
    targetRevision: main
    path: hello-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: analytics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true