apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics
spec:
  type: LoadBalancer
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000