apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PandhuWibowo/apps-manifest.git
    path: ./app-deployment/analytics-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: analytics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true