apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatial-service-deployment
  namespace: analytics
  labels:
    app: spatial-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spatial-service
  template:
    metadata:
      labels:
        app: spatial-service
    spec:
      containers:
        - name: spatial-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Use Helm placeholders
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
