apiVersion: v1
kind: Service
metadata:
  name: spatial-service-service
  namespace: analytics
spec:
  type: ClusterIP
  selector:
    app: spatial-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000