apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-deployment
  namespace: analytics
  labels:
    app: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Use Helm placeholders
          imagePullPolicy: "{{ .Values.image.pullPolicy | default 'Always' }}"
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
