apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: analytics
spec:
  type: LoadBalancer
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000